[project]
name = "cloud-9"
version = "0.1.0"
dependencies = [
  "PyQt6",
  "PyQt6-QScintilla",
  "pygame",
  "requests",
  "sqlite3",
  "huggingface_hub",
  "PyPDF2",
  "docx"
]

extend-exclude = [
    "*.pyc",
    "__pycache__",
]
